### PR TITLE
Cleanup + added globOptions in order to provide extra options to the glob.sync call

### PR DESCRIPTION
**Pull request by Milanzor**
Hey there!

I cleaned up your file to make the code a bit more readable.

Also, I've added a globOptions 4th parameter to the WildcardsEntryWebpackPlugin.entry function, so we can provide extra options to the glob.sync call. 

I did this because I wanted to keep my [file].test.js file next to my entry points, but did not want webpack to pickup those files and compile them. So now i can provide the {ignore: '**/*.test.js} option and the glob will not pick up those files.

Awesome plugin btw, I was looking for exactly this for a long time!

### CODE REVIEW

**Comment by HaNdTriX** [comment]
@8427003 any progress on this?

**Comment by Milanzor** [comment]
@HaNdTriX It didnt feel like owner was gonna look at my PR plus the code was still quite messy and the README was unclear to me. 

I built my own plugin: 
https://github.com/Milanzor/webpack-watched-glob-entries-plugin & https://www.npmjs.com/package/webpack-watched-glob-entries-plugin

Feel free to try and let me know if you have problems!

**Comment by HaNdTriX** [comment]
@Milanzor awesome I'll take a look at it!

**Comment by atav32** [comment]
Appreciate the code cleaning! 

Maybe the author has qualms about blowing away the test dir? (It's not actually unit tests, but *shrug*)

Maybe [Snapshot testing](https://facebook.github.io/jest/docs/en/snapshot-testing.html) like how [`url-loader` does it](https://github.com/webpack-contrib/url-loader/blob/master/test/loader.test.js)?

**Pull request closed without merging**
